FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["backend.csproj", "./"]
RUN dotnet restore "backend.csproj"


COPY . .
RUN dotnet build "backend.csproj" -c Release -o /app/build

# 2. Publikacja
FROM build AS publish
RUN dotnet publish "backend.csproj" -c Release -o /app/publish

# 3. Etap końcowy (Runtime) - ten obraz zostanie uruchomiony
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=publish /app/publish .

# Ustawienie portu na 8081 zgodnie z wymaganiem zadania 04
ENV ASPNETCORE_URLS=http://+:8081
EXPOSE 8081

ENTRYPOINT ["dotnet", "backend.dll"]
